### PR TITLE
Style Change 

### PR DESCRIPTION
**Pull request by asagilmore**
Some simple style changes that make the website more user friendly. 

changed canvas to automatically fit window size, rearranged items.

### CODE REVIEW

**Comment by arokem** [comment]
This looks good to me. 

Not directly related to this PR, but I am not managing to deploy the website locally on my machine. IIUC, all I have to do is run: 


   npm install 
   npm run build 

And the website should show up in `./dist`, but when I do that I get an html file that resembles the one that we see on the netlify automated deployment, and no website. I suspect something here is misconfigured, and I will continue to investigate.

**Comment by asagilmore** [comment]
> This looks good to me.
> 
> Not directly related to this PR, but I am not managing to deploy the website locally on my machine. IIUC, all I have to do is run:
> 
> npm install npm run build
> 
> And the website should show up in `./dist`, but when I do that I get an html file that resembles the one that we see on the netlify automated deployment, and no website. I suspect something here is misconfigured, and I will continue to investigate.

The built website may not be working locally because the publicPath in vue.config.js is set to the github directory name for github pages deployment, instead of your local path.

**Comment by arokem** [comment]
Thanks!  I can now get this working locally. 

I think that maybe this can be done by adding some more code to the vue.config.js file. See #32 for a first pass attempt.

**Comment by arokem** [comment]
Could you please rebase this on top of the main branch, so that I can see the netlify preview before merging?

**Comment by arokem** [comment]
If that comment didn't make sense, try the following: 

1. Make sure that there are no uncommitted changes on your branch. 
2. If there are uncommitted changes, commit them and push them here. 

3. Do the following: 
```
git checkout main
git pull upstream main 
git push origin main
git checkout style_change
git merge main
git push origin style_change
```

Hopefully this should proceed without any conflicts, given changes on main are in other files.

**Comment by asagilmore** [comment]
I rebased to the main branch i think, let me know if that works

**Comment by arokem** [comment]
Did you push after the rebase? I don't see the changes in the vue.config.js file on your branch.

**Comment by arokem** [comment]
Also, another possibility: did you `git pull upstream main` on the `main` branch before starting the rebase?

**Pull request merged**
